### ISSUE TITLE
lauch torpedo ubuntu when stateup action

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megamd#200]
it: \"\"\n  envs: []\n  address: null\nstatus: bootstrapped\n]" 
time="2016-01-21T19:29:45+05:30" level=debug msg="\x1b[1;36;10mSTATEUP CARTON AMS1301955604474101760\x1b[0m" 
time="2016-01-21T19:29:45+05:30" level=debug msg="\x1b[1;37;10m==> pipeline [2]\x1b[0m" 
time="2016-01-21T19:29:45+05:30" level=debug msg="\x1b[1;32;10m  => step 0: change-state-machine action\x1b[0m" 
time="2016-01-21T19:29:45+05:30" level=debug msg="  change state of machine (looneyies.megambox.com, stateup)" 
time="2016-01-21T19:29:45+05:30" level=debug msg="  change state of machine (looneyies.megambox.com, stateup)" 
time="2016-01-21T19:29:45+05:30" level=debug msg="  pub to machine (looneyies.megambox.com, {\"id\":\"\",\"name\":\"\",\"cat_id\":\"ASM1301955604448935936\",\"action\":\"stateup\",\"category\":\"state\",\"created_at\":\"2016-01-21 19:29:45.445557339 +0530 IST\"})" 
time="2016-01-21T19:29:45+05:30" level=debug msg="looneyies.megambox.com_log:{21 Jan 16 19:29 IST --- stateto looneyies.megambox.com megd looneyies ASM1301955604448935936}" 
time="2016-01-21T19:29:45+05:30" level=debug msg="\x1b[1;32;10m  => step 1: add-new-route action\x1b[0m" 
ERR   12 (103.56.92.4:4150) IO error - EOF
time="2016-01-21T19:29:45+05:30" level=debug msg="route53 ready" 
time="2016-01-21T19:29:45+05:30" level=debug msg="looneyies.megambox.com_log:{21 Jan 16 19:29 IST ---- Adding route to machine (looneyies.megambox.com, 103.56.92.48) megd looneyies ASM1301955604448935936}" 
ERR   14 (103.56.92.4:4150) IO error - EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x85aab1]

goroutine 846 [running]:
github.com/karlentwistle/route53.getBody(0xcfc2c0, 0x40, 0xc820755980, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/megam/.go/src/github.com/karlentwistle/route53/route53.go:71 +0x2e1
github.com/karlentwistle/route53.(*AccessIdentifiers).zoneXML(0xc8202f45a0, 0xcfc2c0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/megam/.go/src/github.com/karlentwistle/route53/access_identifiers.go:57 +0x67
github.com/karlentwistle/route53.(*AccessIdentifiers).Zones(0xc8202f45a0, 0x0, 0x0, 0x0)
	/home/megam/.go/src/github.com/karlentwistle/route53/access_identifiers.go:49 +0x76
github.com/megamsys/megamd/router/route53.(*route53Router).zoneMatch(0xc8202f4580, 0x0, 0x0, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/megamd/router/route53/router.go:150 +0xd9
github.com/megamsys/megamd/router/route53.route53Router.SetCName(0x0, 0x0, 0x0, 0x0, 0xc82014b2e0, 0x14, 0xc82010fef0, 0x28, 0x0, 0x0, ...)
	/home/megam/code/workspace/go/src/github.com/megamsys/megamd/router/route53/router.go:52 +0x104
github.com/megamsys/megamd/router/route53.(*route53Router).SetCName(0xc8202f4500, 0xc8207b9c20, 0x16, 0xc8207a9190, 0xc, 0x0, 0x0)
	<autogenerated>:1 +0xf9
github.com/megamsys/megamd/provision/one.glob.func16(0xb7db60, 0xc8202f4480, 0xc8207a3480, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/megamd/provision/one/actions.go:260 +0x3f7
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc8207b9960, 0xc8207a3480, 0x1, 0x1, 0x0, 0x0)
	/home/megam/code/workspace/go/src/github.com/megamsys/libgo/action/action.go:147 +0xc4c
github.com/megamsys/megamd/provision/one.(*oneProvisioner).SetState(0xc82010eba0, 0xc820470c60, 0x7f41841b4e38, 0xc8207b98e0, 0xbeca80, 0x7, 0x0, 0x0)

**Comment by indykish** [comment]
The issue is "During a stateup, the vm failed to insert in Route53". This bug is in **karlentwistle/route53** library.

**Comment by indykish** [comment]
### This code in https://github.com/karlentwistle/route53/blob/master/route53.go

```
if err == nil {
		req.Header = headers
		resp, err := client.Do(req)
		defer resp.Body.Close()
		if err == nil {
			return ioutil.ReadAll(resp.Body)
		}
	}
```

`defer resp.Body is nil`, hence this needs to be changed to 

### Fix 
```go
if err == nil {
		req.Header = headers
		resp, err := client.Do(req)
               if resp.Body !=nil {
		defer resp.Body.Close()
               }  
		if err == nil {
			return ioutil.ReadAll(resp.Body)
		}
	}
```

**Comment by indykish** [comment]
Will be covered in the 2.0 rewrite using our own dns.
